### ISSUE TITLE
英文网页上的Enter或Android会自动变成”回车“或”安卓“

### ISSUE THREAD

**Issue by wqjkdqj** [tongwentang/tongwen-dict#16]
英文网页上的Enter或Android会自动变成”回车“或”安卓“，这个没找到设置，请问在哪里可以

- 设置单词列表
- 或者 建议默认只进行繁体中文至简体中文的转换，英文词不用转
- 或者 设置英文网页不转换

**Comment by t7yang** [comment]
辭庫的有獨立的 repo
新的機制會把一些已知可互換的詞彙對應表用程式做對調產生給簡體用。
基於中國跟台灣的文化差異，在維護時我們只能根據我們認知去處理，不敢保證一定符合中國那邊的用法。
這部分有什麼參考的依據來說明 Enter/Android 這類的詞彙轉或不轉比較好嗎？
我自己閱讀中國文章的理解是中國人更習慣把所有辭彙都進行翻譯，但也不十分確定就是這樣。
方便的話再麻煩補充說明，感謝。

**Comment by wqjkdqj** [comment]
> 

I ignored this issue by setting Auto Convert off to avoid converting "Android" to "安卓" on English page. I saw a fix in eeca836 which only allow s2t. Thanks for your effort.
