### ISSUE TITLE
黑山（國名）

### ISSUE THREAD

**Issue by t7yang** [tongwentang/tongwen-dict#23]
> Bi Cheng2 天前
> 黑山沒必要翻成蒙特內哥羅，因為蒙特內哥羅是特紙那個國家，但很多黑山出現的地方不是在說那邊也被翻了...
> 像是黑山老妖會變成蒙特內哥羅老妖、黑山軍會變成蒙特內哥羅軍、黑山礦坑會變成蒙特內哥羅礦坑、黑山羊最好笑會變成蒙特內哥羅羊，我一開始還跑去查是不是真的有這種羊
> 老實說遇上真的是在講蒙特內哥羅的情況遠小於其實人家就是一個叫黑山的地名

@zhtw2013 覺得如何？

**Comment by zhtw2013** [comment]
這個部分我會PR移除 
另外我還會把之前找到部分容易誤轉的詞彙一同移除
預計本週完成PR
